[project]
title = "Rubin Science Platform"
copyright = "2018–2025 Association of Universities for Research in Astronomy, Inc. (AURA)"
base_url = "https://rsp.lsst.io"
github_url = "https://github.com/lsst/rsp_lsst_io"
version = "Current"

[sphinx]
extensions = ["sphinx_jinja", "sphinxcontrib.youtube"]

[sphinx.intersphinx.projects]
python = "https://docs.python.org/3/"

[sphinx.linkcheck]
ignore = [
    'https://rsp.lsst.io',
    'https://github.com/lsst-rsp/rsp_lsst_io',
    'https://base-lsp.lsst.codes',
    'https://data-dev.lsst.cloud',
    'https://data-int.lsst.cloud',
    'https://data.lsst.cloud',
    'https://summit-lsp.lsst.codes',
    'https://tucson-teststand.lsst.codes',
    'https://usdf-rsp-dev.slac.stanford.edu',
    'https://usdf-rsp.slac.stanford.edu',
    'https://docushare.lsst.org',
    'https://www.java.com/en/',  # Not accessible to the link checker
    'https://ui.adsabs.harvard.edu/abs/2022SPIE12189E..11J/abstract',
    'https://www.star.bris.ac.uk/~mbt/topcat/', # MLG added; frequently times out
]
